data:
  string: "foobar"
  array:
    - John
    - Sarah
  hash: { key: value }
  paragraph: |
    foo
    bar

uplink:
  server: "irc.malkier.net"
  port: 6667
  password:

irc:
  nickname: "iobot"
  username: "iobot"
  realname: "iobot"
